apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: "Application secrets for cilium in k3s/kube-system"
metadata:
  createdAt: "2026-05-26T16:14:03.620Z"
  updatedAt: "2026-05-26T16:14:03.620Z"
config:
  cluster: k3s
  namespace: kube-system
  app: cilium
vault:
  kvMount: secret
  kvPath: k3s/kube-system/cilium
  authMount: k3s
  role: vso-k3s-kube-system-cilium
  boundServiceAccount: sa-cilium
secrets:
  - key: KEY_API
    description: "This is the cilium api key"
    rotationDays: 90
