apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: "Application secrets for cilium in k3s/kube-system"
metadata:
  createdAt: "2026-05-26T14:41:13.565Z"
  updatedAt: "2026-05-26T14:41:13.565Z"
config:
  cluster: k3s
  namespace: kube-system
  app: cilium
vault:
  kvMount: secret
  kvPath: k3s/kube-system/cilium
  authMount: k3s
  role: vso-k3s-kube-system-cilium
  boundServiceAccount: sa-cilium
secrets:
  - key: SECRET_KEY
    generate: true
    length: 64
    description: "Cilium secret key."
    rotationDays: 5
  - key: TLS_KEY
    generate: true
    length: 64
    format: hex
    description: "Cilium enc key."
    rotationDays: 90
