apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: Application secrets for cilium in k3s/kube-system
metadata:
  createdAt: "2026-05-26T16:14:03.620Z"
  updatedAt: "2026-05-26T16:31:57.957Z"
config:
  cluster: k3s
  namespace: kube-system
  app: cilium
vault:
  kvMount: secret
  kvPath: k3s/kube-system/cilium
  authMount: k3s
  role: vso-k3s-kube-system-cilium
  boundServiceAccount: sa-cilium
secrets:
  - key: KEY_API
    value: ""
    description: This is the cilium api key
    rotationDays: 90
  - key: SECRET_KEY
    generate: true
    length: 64
    format: base64
    description: This is cilium secret key!
    rotationDays: 5
