apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: Application secrets for metrics-server in internal/kube-system
metadata:
  createdAt: "2026-05-26T16:37:01.193Z"
  updatedAt: "2026-05-26T16:41:45.086Z"
config:
  cluster: internal
  namespace: kube-system
  app: metrics-server
vault:
  kvMount: secret
  kvPath: internal/kube-system/metrics-server
  authMount: internal
  role: vso-internal-kube-system-metrics-server
  boundServiceAccount: sa-metrics-server
secrets: []
