apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: Application secrets for metrics-server in internal/kube-system
metadata:
  createdAt: "2026-05-26T16:37:01.193Z"
  updatedAt: "2026-05-27T12:30:57.254Z"
config:
  cluster: internal
  namespace: kube-system
  app: metrics-server
vault:
  kvMount: secret
  kvPath: internal/kube-system/metrics-server
  authMount: internal
  role: vso-internal-kube-system-metrics-server
  boundServiceAccount: sa-metrics-server
secrets:
  - key: NEW_KEY
    generate: true
    length: 64
    format: hex
    description: new test key!
    rotationDays: 3
  - key: KEY
    value: ""
    description: Imported from Vault, descriptions!
    rotationDays: 30
  - key: API_KEY
    value: ""
    description: API key to call metrics, descriptions extended!
    rotationDays: 2
