projectName: sag
repoURL: git@github.com:sadra-group/infra-code.git
targetRevision: main
destinationServer: https://kubernetes.default.svc
environment: prod
apps:
  kps:
    enabled: false
    extraPath: clusters/sag/prod/values/kube-prometheus-stack
  ak:
    enabled: false
    namespace: ak
    extraSources:
      - repoURL: git@github.com:sadra-group/infra-code.git
        targetRevision: main
        path: charts/ak-bp
        helm:
          valueFiles:
            - ../../clusters/sag/prod/values/ak-bp-values.yaml
  vault:
    enabled: false
    extraPath: clusters/sag/prod/values/vault
  vso:
    enabled: false
    namespace: vso
    extraPath: clusters/sag/prod/values/vso
  cnpg:
    enabled: false
  outline:
    enabled: false
  olm:
    enabled: false
    namespace: operator-lifecycle-manager
    syncWave: 5
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  odoo:
    enabled: true
    namespace: odoo
    syncWave: 20
  moodle:
    enabled: true
    namespace: moodle
    syncWave: 20
  pdmdb-instances:
    enabled: true
  valkey-instances:
    enabled: true
    instances:
      - name: valkey-odoo
        namespace: odoo
        syncWave: 20
      - name: valkey-aarza
        namespace: aarza
        syncWave: 20
  meilisearch-instances:
    enabled: true
    instances:
      - name: meilisearch-sag
        namespace: mp
        syncWave: 20
  cnpg-instances:
    enabled: true
    instances:
      - name: aarza-pgcluster
        namespace: aarza
        syncWave: 11
      - name: sadra-pg
        namespace: sadra
        syncWave: 11
