{{- $saCreate := coalesce .Values.serviceAccount.create .Values.global.serviceAccount.create false -}}
{{- if $saCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "custom-service.fullname" .) }}
  labels:
    {{- include "custom-service.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
