apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: Application secrets for argocd-image-updater in internal/argocd
metadata:
  createdAt: "2026-05-27T15:22:36.574Z"
  updatedAt: "2026-05-27T15:36:12.496Z"
config:
  cluster: internal
  namespace: argocd
  app: argocd-image-updater
vault:
  kvMount: secret
  kvPath: internal/argocd/argocd-image-updater
  authMount: internal
  role: vso-internal-argocd-argocd-image-updater
  boundServiceAccount: sa-argocd-image-updater
secrets:
  - key: RANDOM
    parent: internal/kube-system/metrics-server/KEY
    description: This is a test to see if the we can copy from connects/ak/authentik/RANDOM
    rotationDays: 90
  - key: GENERATED
    generate: true
    length: 64
    rotationDays: 90
  - key: SET
    value: ""
    rotationDays: 90
