apiVersion: platform.secrets/v1alpha1
kind: VaultAppSecret
description: "Application secrets for k in k3s/monitoring/kps.yaml"
metadata:
  createdAt: "2026-06-04T22:59:41.543Z"
  updatedAt: "2026-06-04T22:59:41.543Z"
config:
  cluster: k3s
  namespace: monitoring
  app: kps
vault:
  kvMount: secret
  kvPath: k3s/monitoring/kps
  authMount: k3s
  role: vso-k3s-monitoring-kps
  boundServiceAccount: sa-kps
secrets:
  - key: GRAFANA_PASSWORD
    generate: true
    length: 64
    description: "This is the grafana default admin password"
    rotationDays: 90
