{{- $configJson := include "mychart.getConfig" . -}}
{{- $config := $configJson | fromJson -}}
---
{{- if $config.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}