clusterName: k3s
repoURL: https://github.com/FHSAF/cs-cg.git
targetRevision: main
destinationServer: https://kubernetes.default.svc
projects:
  - name: argocd-dev-project
    enabled: true
    description: Development environment resources
    destinations:
      - namespace: dev
        server: https://kubernetes.default.svc
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
    roles:
      - name: k3s-stage-argocd-admins
        description: Full Admin access for K3s Stage Team
        policies:
          - resources:
              - applications
              - applicationsets
              - repositories
              - logs
              - exec
            verbs:
              - "*"
            objects:
              - "*"
      - name: k3s-stage-argocd-viewers
        description: Read-only access
        policies:
          - resources:
              - applications
              - logs
            verbs:
              - get
              - list
            objects:
              - "*"
  - name: argocd-stage-project
    enabled: true
    description: Stage environment resources
    destinations:
      - namespace: stage
        server: https://kubernetes.default.svc
    roles:
      - name: k3s-stage-argocd-admins
        policies:
          - resources:
              - "*"
            verbs:
              - "*"
            objects:
              - "*"
      - name: k3s-microservices-operators-stage
        policies:
          - resources:
              - applications
              - logs
            verbs:
              - get
              - sync
            objects:
              - stage-*
apps:
  metrics-server:
    enabled: true
  argocd:
    enabled: true
  certificate:
    enabled: true
    namespace: traefik
    syncWave: "3"
    project: default
    sources:
      - repoURL: "{{ .Values.repoURL }}"
        targetRevision: "{{ .Values.targetRevision }}"
        path: clusters/{{ .Values.clusterName }}/_core/values/certificates
